{% extends "skeleton.phtml" %}

{# Codes in this section will be put between <head></head> tags. #}
{% block head %}
{% endblock %}

{# Part of title. Final title will be "StarCloud - {partOfTitle}" #}
{% block title %}Detail{% endblock %}

{# The main content except head tabs. #}
{% block content %}
{% endblock %}

{# Codes in this section will be put after body content. #}
{% block script %}
{% endblock %}
